version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app                    
      - app_node_modules:/app/node_modules  
    env_file:
      - .env                      
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && exec npm run dev"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tugas-docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  app_node_modules:
